### ISSUE TITLE
TypeError occurred when gohttp was run on Python 3.5 environment

### ISSUE THREAD

**Issue by t2y** [shazow/gohttplib#10]
I tried to run on py35 environment, but an error was occurred as below. However, it's running on py27 environment. Is there any issues on my environment?

``` bash
(gohttp)$ make example-python
(gohttp)$ cd examples/python && python gohttp/build_gohttplib.py
(gohttp)$ python -m gohttp
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/t2y/work/external-repo/go/gohttplib/examples/python/gohttp/__main__.py", line 4, in <module>
    @route('/')
  File "/Users/t2y/work/external-repo/go/gohttplib/examples/python/gohttp/__init__.py", line 59, in wrapped
    lib.HandleFunc(pattern, handler)
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

```

**Comment by shazow** [comment]
Pushed out a fix, sorry about that. :)

Needed more bytes, fewer strings.

**Comment by t2y** [comment]
It works. Thanks!

**Comment by shazow** [comment]
:custard:
